;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Cum Mar 11 2016
; Processor: 8086
; Compiler:  MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================
STAK    SEGMENT PARA STACK 'STACK'
        DW 20 DUP(?)
STAK    ENDS

DATA    SEGMENT PARA 'DATA'
DIGITS  DB 00H
ISIM	DB 5AH, 45H, 59H, 4EH, 45H, 50H
DATA    ENDS

CODE    SEGMENT PARA 'CODE'
        ASSUME CS:CODE, DS:DATA, SS:STAK
START:
        MOV AX, DATA
	MOV DS, AX
	
	MOV DX, 0302h 
	MOV AL, 01001101B ;asenkron olacak şekilde yani son iki bit 00'dan farkli olacak sekilde ayarliyoruz
	OUT DX, AL
	
	MOV AL, 40H ;kontrol yazmaci ile 8251'i resetliyoruz
	OUT DX, AL
	
	MOV AL, 01001101B ; 8 veri biti ve 1 carpan olacak sekilde mod yazmacini ayarladik 
	OUT DX, AL
	
	MOV AL, 00010101B ;hem receive hem transmit ozelligi aktif hale getiriyoruz
	OUT DX, AL
	

ENDLESS:

	MOV DX, 0302H ;durum yazmaci adresi 
TEKRAR:
	IN AL, DX
	AND AL, 02H
	JZ TEKRAR ; durum yazmacini okuyup RxRDY biti 1 olmadigi surece(yani receive etmeye hazir hale gelene kadar) kontrol edip tekrarliyoruz
	
	MOV DX, 0300H ;veri yazmaci adresi
	IN AL, DX ;disaridan girilen degeri okuyoruz 
	SHR AL,1
	
	MOV CL, AL ;disaridan girilen degeri bir yazmaca atadik 
	AND CX,000FH ;disaridan gelen degeri ascii olarak aldigi icin ve bize decimal hali lazim oldugundan 000F ile andliyoruz 
	
L1:	XOR SI,SI ;indis icin kullanacagimiz yazmacin degerini sifirliyoruz

YAZDIR:
TEKRAR3:
	MOV DX, 0302H ;durum yazmaci adresi
        IN AL, DX 
	AND AL, 01H ;durum yazmacini okuyup TxRDY degeri bir olana kadar kontrol edip tekrarliyoruz(yani transmit islemine hazir hale gelinceye kadar)
	JZ TEKRAR3
	
	MOV DX, 0300H ;veri yazmaci adresi 
	MOV AL,ISIM[SI] 
	OUT DX, AL ;ismimizin harflerinden olusan dizinin elemanlarini sirasiyla gonderiyoruz
	INC SI ;her bir harften sonra indis degerini 1 arttiriyoruz
	CMP SI,07H ;ismin tamami yazilmis diye kontrol
	JNZ YAZDIR ;ismin tamami yazilana kadar islemleri tekrarliyoruz
	LOOP L1 ;disaridan girilen deger kadar isim ekrana yazdiriliyor

	
        JMP ENDLESS
CODE    ENDS
        END START