Lab 1
;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Per Şub 11 2016
; Processor: 8086
; Compiler:  MASM32
;START ENDP  MOV AX, DATA
 ;     MOV DS, AX
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================
CODE    SEGMENT PUBLIC 'CODE'
	 ORG 100H
        ASSUME CS:CODE, SS:CODE, DS:CODE

START: JMP BASLA

DIGITS 	DB 88H, 83H, 0C6H, 0A1H

BASLA: 
        ; Write your code here
	mov dx, 306h ; control word adresini atadık 
	mov al, 90h ; control word'umuzun degerini atadık 
	out dx, al 
	MOV BX,0H ; BX yazmacını dizide kullanmak icin sifirliyoruz
	
	MOV DX,302H
	MOV AL, 0FFH
	OUT DX,AL

ENDLESS:
	MOV DX,300H ; PORT A'nin adresini atadik 
	IN AX,DX ;PORT A 'dan deger okuyoruz
	CMP AX,0EEH ;butona basilip basilmadigini kontrol ediyoruz
	JZ ENDLESS ;butona basilana kadar sonsuz dongu
	CMP AX,0EFH ; sifirinci butona basilmis mi diye bakiyoruz
	JZ BUTONBIR ; CMP islemi sonucu 0 ise sifirinci butona basilmis
		    ; eger sifirinci butona basilmadiyse dorduncu butona basilmis buradan devam ediyor
	MOV DX,302H ; PORT B adresini atadik 
	MOV AL,0C0H ; dorduncu buton gostergeyi sifirlamak icindi 
	OUT DX,AL ; sifir degerini gostergede gosteriyoruz
	XOR BX,BX ; dizi indisimizi sifirliyoruz (gosterge sifirlandigi icin)
	JMP ENDLESS 
	
BUTONBIR: 
	MOV DX,300H ;PORT A adresini atadik 
	IN AX,DX ;PORT A' dan degerleri aldik 
	CMP AX,0EEH ;butonun bir kere basilmasinin kontrolu
	JNE BUTONBIR 
	  CMP BX,04H ;dizide sona gelip gelmedigimizin kontrolu
	  JNZ DEVAM
	  MOV BX,0H ; dizide sona gelindiyse indisi sifirliyoruz 
DEVAM:	 
	 MOV DX,302H ;PORT B'nin adresini atadik
	 MOV AL,DIGITS[BX] ;gostergede gosterilecek olan elemani atadik 
	 OUT DX,AL ; gostergeden degerimizi goruyoruz
	 INC BX ; indis degerini arttirdik
	 JMP ENDLESS
	RET 
;START 	ENDP



CODE    ENDS
        END START
